version: '3.4'

services:
  myshopdbcontainer:
    image: postgres:latest
    environment:
      POSTGRES_DB: myshop
      POSTGRES_USER: postgresusr
      POSTGRES_PASSWORD: postgrespwd
    volumes:
      - ./MyShop.Persistence/MyShop.Persistence/Databases/Postgres/Scripts/init_schema.sql:/docker-entrypoint-initdb.d/1-init_schema.sql
      - ./MyShop.Persistence/MyShop.Persistence/Databases/Postgres/Scripts/init_data.sql:/docker-entrypoint-initdb.d/2-init_data.sql
    ports:
      - "5432:5432"
      
  myshop.api:
    image: ${DOCKER_REGISTRY-}myshopapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on: ["myshopdbcontainer"]
